[project]
name = "ComfyUI-GadgetNodes"
description = "A collection of utility nodes for ComfyUI to streamline workflows, including prompt editing, translation, model preset management, image preprocessing, and metadata editing."
version = "0.0.1"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/2daadv/ComfyUI-GadgetNodes"

[tool.comfy]
PublisherId = "dadaadv"
DisplayName = "ComfyUI-GadgetNodes"
