[project]
name = "ComfyUI-GadgetNodes"
description = "Utility nodes for model, prompt, image, train, group, logic, etc."
version = "0.0.1"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/2daadv/ComfyUI-GadgetNodes"

[tool.comfy]
PublisherId = "2daadv"
DisplayName = "ComfyUI-GadgetNodes"
